version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    cooldown:
      # Specifically set to 0 for PyAnsys ecosystem related packages
      default-days: 0
      include:
       - ansys-*
       - pyansys-*
       - pyaedt
       - pyedb
       - pygranta
       - pytwin
    groups:
       deps:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
       actions:
          patterns:
            - "*"
