version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
