name: GitHub CI
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: pyansys
  PACKAGE_NAMESPACE: pyansys
  MAIN_PYTHON_VERSION: '3.11'
  DOCUMENTATION_CNAME: "docs.pyansys.com"
  # attrs,referencing,jeepney - This has MIT license but fails the check
  # paramiko,psycopg,psycopg-binary - LGPL licenses, being used by ansys-dynamicreporting-core and ansys-turbogrid-core
  LICENSE_WHITELISTING: "attrs,referencing,jeepney,paramiko,psycopg,psycopg-binary"

jobs:

  check-licenses:
    name: Check depencencies' licenses
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - name: PyAnsys Licenses Check
        uses: ansys/actions/check-licenses@maint/revert-to-original-pip-licenses
        with:
          python-version: ${{ matrix.python-version }}
          target: "all"
          whitelist-license-check: ${{ env.LICENSE_WHITELISTING }}
