  release:
    name: Release project
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [package, smoke-tests-extras, wheelhouse-all]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release to PyPI repository
        uses: ansys/actions/release-pypi-public@v10
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          twine-username: __token__
          twine-token: ${{ secrets.PYPI_TOKEN }}

      - name: Release to GitHub
        uses: ansys/actions/release-github@v10
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          additional-artifacts: 'all-deps-Linux-3.10 all-deps-Linux-3.11 all-deps-Linux-3.12 all-deps-Linux-3.13 all-deps-Windows-3.10 all-deps-Windows-3.11 all-deps-Windows-3.12 all-deps-Windows-3.13 all-deps-macOS-3.10 all-deps-macOS-3.11 all-deps-macOS-3.12 all-deps-macOS-3.13'
          token: ${{ secrets.GITHUB_TOKEN }}

  docs-release:
    name: Deploy release docs
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Deploy the latest release documentation
        uses: ansys/actions/doc-deploy-stable@v10
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  adapt-landing-page-release:
    uses: ./.github/workflows/update-gh-pages.yml
    needs: [docs-release]
    secrets: inherit


