  doc-deploy-dev:
      name: "Deploy development docs"
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: [package]
      steps:
        - name: Deploy the latest documentation
          uses: ansys/actions/doc-deploy-dev@v10
          with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
            bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
            bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  adapt-landing-page-dev:
    uses: ./.github/workflows/update-gh-pages.yml
    needs: [doc-deploy-dev]
    secrets: inherit
