name: Dependency Reviewer

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: low
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          allow-licenses: Apache-2.0, PSF-2.0, HPND, BSD-3-Clause, MIT
